### PR TITLE
Parse numbers from decimal, octal and hexadecimal number systems.

### PR DESCRIPTION
**Pull request by azaparov**
By default accepting all supported numerical systems. For specific arguments numerical system can be specified explicitly with additional wrapper class "NumericalBase. See README.md

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Very cool - thanks!

**Comment by FlorianRappl** [comment]
🍺

**Comment by azaparov** [comment]
Great. I could not make test cases to run on my system. Something is wrong with catch2 header file and bii seems outdated. But it’s worth adding test case if you can make it run.

**Comment by azaparov** [comment]
:)

**Comment by FlorianRappl** [comment]
Yeah bii is unfortunately dead. We can, however, just switch to a fixed version of catch.

**Pull request merged**
